<?php

return [
  'eway_recurring_contribution_max_retry' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_max_fail_attempts',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '3',
    'description' => 'Maximum number of retries for failed eWay recurring contributions.',
    'title' => 'Maximum Number of Retries',
    'help_text' => 'Maximum number of retries for failed eWay recurring contributions.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_contribution_retry_delay' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_retry_delay',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '4',
    'description' => 'Number of days after CiviCRM should retry recurring payment.',
    'title' => 'Retry delay (in days)',
    'help_text' => 'Number of days after CiviCRM should retry recurring payment.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_keep_sending_receipts' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_keep_sending_receipts',
    'type' => 'Boolean',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'title' => 'Send receipt for all recurring contributions',
    'help_text' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'html_type' => 'checkbox',
    'quick_form_type' => 'YesNo',
  ],
  'eway_settlement_window_days' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_settlement_window_days',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '10',
    'description' => 'Settlement sync window, in days back from today. Bounds both (a) which Completed eWAY contributions are treated as still awaiting reconciliation and (b) how many calendar days of eWAY settlement reports are queried each run. Sized to cover eWAY settlement lag (mostly 24-72h, occasionally overnight) plus a weekend margin. Contributions older than this drop out of the sync; standard manual reconciliation owns them.',
    'title' => 'Settlement Sync: Window (days)',
    'help_text' => 'Days back from today for the settlement sync window. Covers both contribution candidacy and the eWAY settlement report date range.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 10,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_settlement_sync_mode' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_settlement_sync_mode',
    'type' => 'String',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 'live',
    'title' => 'Settlement Sync: Mode',
    'description' => 'Controls which payment processors are included in the settlement sync: "live", "test", or "both". Non-UI dev/QA setting; defaults to "live". Only useful where the eWAY sandbox settlement API returns data (it currently does not), so test/both are of limited value. Set via API or Civi::settings()->set() if needed.',
    'pseudoconstant' => [
      'callback' => 'CRM_eWAYRecurring_SettlementSync::getModeOptions',
    ],
  ],
];
