<?php

return [
  'eway_recurring_contribution_max_retry' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_max_fail_attempts',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '3',
    'description' => 'Maximum number of retries for failed eWay recurring contributions.',
    'title' => 'Maximum Number of Retries',
    'help_text' => 'Maximum number of retries for failed eWay recurring contributions.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_contribution_retry_delay' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_contribution_retry_delay',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '4',
    'description' => 'Number of days after CiviCRM should retry recurring payment.',
    'title' => 'Retry delay (in days)',
    'help_text' => 'Number of days after CiviCRM should retry recurring payment.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 50,
    ],
    'quick_form_type' => 'Element',
  ],
  'eway_recurring_keep_sending_receipts' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_recurring_keep_sending_receipts',
    'type' => 'Boolean',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '0',
    'description' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'title' => 'Send receipt for all recurring contributions',
    'help_text' => 'Whether to keep sending CiviCRM receipt/invoice after initial contribution. User will continue to receive receipts from eWay regardless of this setting.',
    'html_type' => 'checkbox',
    'quick_form_type' => 'YesNo',
  ],
  'eway_settlement_sync_lookback_days' => [
    'group_name' => 'eWay Recurring Settings',
    'group' => 'eWAYRecurring',
    'name' => 'eway_settlement_sync_lookback_days',
    'type' => 'Integer',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => '5',
    'description' => 'Number of days for settlement sync: used for both (a) querying unreconciled contributions and (b) the eWAY Settlement API date range. Most settlement data is available after ~3 business days; 5 days provides a buffer.',
    'title' => 'Settlement Sync: Lookback Days',
    'help_text' => 'Number of days for settlement sync. Used for both contribution lookback and eWAY API date range.',
    'html_type' => 'Text',
    'html_attributes' => [
      'size' => 10,
    ],
    'quick_form_type' => 'Element',
  ],
];
